export enum Element {
    H = "H",
    He = "He",
    Li = "Li",
    Be = "Be",
    B = "B",
    C = "C",
    N = "N",
    O = "O",
    F = "F",
    Ne = "Ne",
    Na = "Na",
    Mg = "Mg",
    Al = "Al",
    Si = "Si",
    P = "P",
    S = "S",
    Cl = "Cl",
    Ar = "Ar",
    K = "K",
    Ca = "Ca",
}

export enum Category {
    AlkaliMetal = "Alkali Metal",
    AlkalineEarthMetal = "Alkaline Earth Metal",
    TransitionMetal = "Transition Metal",
    PostTransitionMetal = "Post-Transition Metal",
    Metalloid = "Metalloid",
    NonMetal = "Non-Metal",
    Halogen = "Halogen",
    NobleGas = "Noble Gas",
}

export enum Origin {
    TheBigBang = "The Big Bang",
    CosmicRayCollisions = "Cosmic Ray Collisions",
    DyingLowMassStars = "Dying Low Mass Stars",
    DyingHighMassStars = "Dying High Mass Stars",
    WhiteDwarfSupernovae = "White Dwarf Supernovae",
    MergingNeutronStars = "Merging Neutron Stars",
    RadioactiveDecay = "Radioactive Decay",
    HumanMade = "Human Made",
}

export enum Country {
    UK = "UK",
    USA = "USA",
    Germany = "Germany",
    France = "France",
    Sweden = "Sweden",
    Denmark = "Denmark",
    Other = "Other",
}

export enum Color {
    Colorless = "Colorless",
    Silver = "Silver",
    SlateGray = "Slate Gray",
    Black = "Black",
    Yellow = "Yellow",
    Gray = "Gray",
    Copper = "Copper",
    Red = "Red",
    Gold = "Gold",
}

export interface ElementData {
    name: Element;
    category: Category;
    period: number;
    group: number;
    origins: Origin[];
    countries: Country[];
    color: Color;
}

export enum ElementProperty {
    Category = "Category",
    Period = "Period",
    Group = "Group",
    Origins = "Origins",
    Countries = "Countries",
    Color = "Color",
}

export const Elements: ElementData[] = [
    {
        name: Element.H,
        category: Category.NonMetal,
        period: 1,
        group: 1,
        origins: [Origin.TheBigBang],
        countries: [Country.UK],
        color: Color.Colorless,
    },
    {
        name: Element.He,
        category: Category.NobleGas,
        period: 1,
        group: 18,
        origins: [Origin.TheBigBang],
        countries: [Country.France, Country.UK],
        color: Color.Colorless,
    },
    {
        name: Element.Li,
        category: Category.NobleGas,
        period: 2,
        group: 1,
        origins: [Origin.DyingLowMassStars],
        countries: [Country.Sweden],
        color: Color.Silver,
    },
    {
        name: Element.Be,
        category: Category.NobleGas,
        period: 2,
        group: 2,
        origins: [Origin.CosmicRayCollisions],
        countries: [Country.France],
        color: Color.SlateGray,
    },
    {
        name: Element.B,
        category: Category.NobleGas,
        period: 2,
        group: 13,
        origins: [Origin.CosmicRayCollisions],
        countries: [Country.France],
        color: Color.Black,
    },
    {
        name: Element.C,
        category: Category.NobleGas,
        period: 2,
        group: 14,
        origins: [Origin.DyingLowMassStars],
        countries: [Country.Other],
        color: Color.Black,
    },
    {
        name: Element.N,
        category: Category.NobleGas,
        period: 2,
        group: 15,
        origins: [Origin.DyingLowMassStars],
        countries: [Country.UK],
        color: Color.Colorless,
    },
    {
        name: Element.O,
        category: Category.NobleGas,
        period: 2,
        group: 16,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.Sweden],
        color: Color.Colorless,
    },
    {
        name: Element.F,
        category: Category.NobleGas,
        period: 2,
        group: 17,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.France],
        color: Color.Colorless,
    },
    {
        name: Element.Ne,
        category: Category.NobleGas,
        period: 2,
        group: 18,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.UK],
        color: Color.Colorless,
    },
    {
        name: Element.Na,
        category: Category.NobleGas,
        period: 3,
        group: 1,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.UK],
        color: Color.Silver,
    },
    {
        name: Element.Mg,
        category: Category.NobleGas,
        period: 3,
        group: 2,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.UK],
        color: Color.Silver,
    },
    {
        name: Element.Al,
        category: Category.PostTransitionMetal,
        period: 3,
        group: 13,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.Denmark],
        color: Color.Silver,
    },
    {
        name: Element.Si,
        category: Category.Metalloid,
        period: 3,
        group: 14,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.Sweden],
        color: Color.Gray,
    },
    {
        name: Element.P,
        category: Category.NonMetal,
        period: 3,
        group: 15,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.Germany],
        color: Color.Colorless,
    },
    {
        name: Element.S,
        category: Category.NonMetal,
        period: 3,
        group: 16,
        origins: [Origin.DyingHighMassStars, Origin.WhiteDwarfSupernovae],
        countries: [Country.Other],
        color: Color.Yellow,
    },
    {
        name: Element.Cl,
        category: Category.Halogen,
        period: 3,
        group: 17,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.Sweden],
        color: Color.Yellow,
    },
    {
        name: Element.Ar,
        category: Category.NobleGas,
        period: 3,
        group: 18,
        origins: [Origin.DyingHighMassStars, Origin.WhiteDwarfSupernovae],
        countries: [Country.UK],
        color: Color.Colorless,
    },
    {
        name: Element.K,
        category: Category.AlkaliMetal,
        period: 4,
        group: 1,
        origins: [Origin.DyingHighMassStars],
        countries: [Country.UK],
        color: Color.Silver,
    },
    {
        name: Element.Ca,
        category: Category.AlkalineEarthMetal,
        period: 4,
        group: 2,
        origins: [Origin.DyingHighMassStars, Origin.WhiteDwarfSupernovae],
        countries: [Country.UK],
        color: Color.Silver,
    },
];